# Generated by Django 5.2.17 on 2026-08-18 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_initial'),
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='REQUESTED', max_length=20)),
                ('response_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_collaborations', to='departments.department')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='reports.report')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supporting_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_collaborations', to='departments.department')),
            ],
        ),
    ]
