# Generated by Django 5.2.17 on 2026-08-19 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(help_text="Action performed, e.g., 'USER_REGISTERED', 'ROLE_UPDATED', 'REPORT_STATUS_CHANGED'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.UUIDField(blank=True, help_text='UUID of the affected entity.', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(help_text="Target model/entity, e.g., 'User', 'Report', 'Task'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_values',
            field=models.JSONField(blank=True, help_text='Snapshot of data after mutation.', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_values',
            field=models.JSONField(blank=True, help_text='Snapshot of data before mutation.', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True, help_text='Optional reason or description for the action.', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user/actor who performed the action. Null if system-generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_logs_action_31f574_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_logs_created_262184_idx'),
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_logs',
        ),
    ]
