# Generated by Django 5.2.17 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assigned_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('ACCEPTED', 'Accepted'),
                    ('IN_PROGRESS', 'In Progress'),
                    ('COMPLETED_PENDING_VERIFICATION', 'Completed Pending Verification'),
                    ('VERIFIED', 'Verified'),
                    ('REJECTED', 'Rejected'),
                    ('REOPENED', 'Reopened'),
                    ('OVERDUE', 'Overdue'),
                    ('CANCELLED', 'Cancelled'),
                ],
                default='PENDING',
                max_length=40,
            ),
        ),
    ]
