# Generated by Django 6.1 on 2026-08-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_admin_feedback_report_ai_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='resolved_at',
        ),
        migrations.AddField(
            model_name='report',
            name='is_deleted_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='is_deleted_by_citizen',
            field=models.BooleanField(default=False),
        ),
    ]
