# Generated by Django 6.1 on 2026-08-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_resolved_at_report_is_deleted_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
