# Generated by Django 5.2.17 on 2026-08-18 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='admin_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='managed_department', to=settings.AUTH_USER_MODEL),
        ),
    ]
